use_frameworks!


source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'AHFMDownloaderManager_Example' do
  pod 'AHFMDownloaderManager', :path => '../'

  target 'AHFMDownloaderManager_Tests' do
    inherit! :search_paths

    
  end
end
